version: "3.8"
services:
  db:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    volumes:
      - postgresdb:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@domain.com
      PGADMIN_DEFAULT_PASSWORD: test1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgresdb:
  pgadmin-data:


